export const LOGIN = 'LOGIN'
export const SIGNUP = 'SIGNUP'

export const GET_MANAGERS_REQUEST = 'GET_MANAGERS_REQUEST'
export const GET_MANAGERS_SUCCESS = 'GET_MANAGERS_SUCCESS'
export const GET_MANAGERS_FAIL = 'GET_MANAGERS_FAIL'

export const POST_MANAGERS_REQUEST = 'POST_MANAGERS_REQUEST'
export const POST_MANAGERS_SUCCESS = 'POST_MANAGERS_SUCCESS'
export const POST_MANAGERS_FAIL = 'POST_MANAGERS_FAIL'

export const PUT_MANAGERS_REQUEST = 'PUT_MANAGERS_REQUEST'
export const PUT_MANAGERS_SUCCESS = 'PUT_MANAGERS_SUCCESS'
export const PUT_MANAGERS_FAIL = 'PUT_MANAGERS_FAIL'

export const DELETE_MANAGERS_REQUEST = 'DELETE_MANAGERS_REQUEST'
export const DELETE_MANAGERS_SUCCESS = 'DELETE_MANAGERS_SUCCESS'
export const DELETE_MANAGERS_FAIL = 'DELETE_MANAGERS_FAIL'

export const GET_COURSE_REQUEST = 'GET_COURSE_REQUEST'
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS'
export const GET_COURSE_FAIL = 'GET_COURSE_FAIL'

export const POST_COURSE_REQUEST = 'POST_COURSE_REQUEST'
export const POST_COURSE_SUCCESS = 'POST_COURSE_SUCCESS'
export const POST_COURSE_FAIL = 'POST_COURSE_FAIL'

export const PUT_COURSE_REQUEST = 'PUT_COURSE_REQUEST'
export const PUT_COURSE_SUCCESS = 'PUT_COURSE_SUCCESS'
export const PUT_COURSE_FAIL = 'PUT_COURSE_FAIL'

export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST'
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS'
export const DELETE_COURSE_FAIL = 'DELETE_COURSE_FAIL'

export const POST_ACCEPT_MANAGER_ADD_REQUEST_REQUEST = 'POST_ACCEPT_MANAGER_ADD_REQUEST_REQUEST'
export const POST_ACCEPT_MANAGER_ADD_REQUEST_SUCCESS = 'POST_ACCEPT_MANAGER_ADD_REQUEST_SUCCESS'
export const POST_ACCEPT_MANAGER_ADD_REQUEST_FAIL = 'POST_ACCEPT_MANAGER_ADD_REQUEST_FAIL'

export const POST_ACCEPT_COURSE_ADD_BY_MANAGER_REQUEST = 'POST_ACCEPT_COURSE_ADD_BY_MANAGER_REQUEST'
export const POST_ACCEPT_COURSE_ADD_BY_MANAGER_SUCCESS = 'POST_ACCEPT_COURSE_ADD_BY_MANAGER_SUCCESS'
export const POST_ACCEPT_COURSE_ADD_BY_MANAGER_FAIL = 'POST_ACCEPT_COURSE_ADD_BY_MANAGER_FAIL'

export const POST_REJECT_MANAGER_ADD_REQUEST_REQUEST = 'POST_REJECT_MANAGER_ADD_REQUEST_REQUEST'
export const POST_REJECT_MANAGER_ADD_REQUEST_SUCCESS = 'POST_REJECT_MANAGER_ADD_REQUEST_SUCCESS'
export const POST_REJECT_MANAGER_ADD_REQUEST_FAIL = 'POST_REJECT_MANAGER_ADD_REQUEST_FAIL'

export const POST_REJECT_COURSE_ADD_BY_MANAGER_REQUEST = 'POST_REJECT_COURSE_ADD_BY_MANAGER_REQUEST'
export const POST_REJECT_COURSE_ADD_BY_MANAGER_SUCCESS = 'POST_REJECT_COURSE_ADD_BY_MANAGER_SUCCESS'
export const POST_REJECT_COURSE_ADD_BY_MANAGER_FAIL = 'POST_REJECT_COURSE_ADD_BY_MANAGER_FAIL'

export const SEARCH_REQUEST = 'SEARCH_REQUEST'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAIL = 'SEARCH_FAIL'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL'

export const GUEST_REQUEST = 'GUEST_REQUEST'
export const GUEST_SUCCESS = 'GUEST_SUCCESS'
export const GUEST_FAIL = 'GUEST_FAIL'

export const POST_TO_REQUEST_MANAGER_REQUEST = 'POST_TO_REQUEST_MANAGER_REQUEST'
export const POST_TO_REQUEST_MANAGER_SUCCESS = 'POST_TO_REQUEST_MANAGER_SUCCESS'
export const POST_TO_REQUEST_MANAGER_FAIL = 'POST_TO_REQUEST_MANAGER_FAIL'

export const POST_REQUEST_TO_ADD_COURSE_REQUEST = 'POST_REQUEST_TO_ADD_COURSE_REQUEST'
export const POST_REQUEST_TO_ADD_COURSE_SUCCESS = 'POST_REQUEST_TO_ADD_COURSE_SUCCESS'
export const POST_REQUEST_TO_ADD_COURSE_FAIL = 'POST_REQUEST_TO_ADD_COURSE_FAIL'